# Generated by Django 5.1.4 on 2025-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_owner_alter_listing_highest_bid_bid_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, default=None),
        ),
    ]
