# Generated by Django 5.1.4 on 2025-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
