# Generated by Django 5.1.4 on 2025-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="listings", to="auctions.category"
            ),
        ),
    ]
