# Generated by Django 5.1.4 on 2025-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_listing_category_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="highest_bid",
            field=models.DecimalField(
                decimal_places=2,
                default=models.DecimalField(decimal_places=2, max_digits=10),
                max_digits=10,
            ),
        ),
    ]
