# Generated by Django 5.1.4 on 2025-09-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_starting_bid_alter_listing_highest_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings_won",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
