# Generated by Django 5.1.4 on 2025-09-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="on",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
