# Generated by Django 5.1.4 on 2025-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_comment_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
